# *** Change name and description for your plugin.
name: sample
description: A minimal example plugin for desktop, in the style of the 'flutter create' plugin template.
version: 0.0.1
author:
homepage:

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: SamplePlugin

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  convert: ^2.1.1
